name: Music Organizer

on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    strategy:
      matrix:
        api-level: [ 29 ]


    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
            key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: create API key
        run: |
          touch ./apikey.properties
          echo API_KEY=\"$API_KEY\" >> ./apikey.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Kotlin Linter
        run: ./gradlew ktlintCheck

      - name: Rund Android Linter
        run: ./gradlew lintDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Run UI / Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Build Debug APK
        run: ./gradlew assembleDebug